/*
 * Generated by MTK Easy PinMux Tool Version 2.3.0 for 7687. Copyright MediaTek Inc. (C) 2015.
 * 2017-08-10 08:16:33:0352
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
