/*
 * Generated by MTK Easy PinMux Tool Version 2.0.1 for 7687. Copyright MediaTek Inc. (C) 2015.
 * 2017-01-27 14:46:43:0506
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/


/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */

const char BSP_CTP_SW_I2C_SCL_PIN = 0xff;
const char BSP_CTP_SW_I2C_SDA_PIN = 0xff;
const char BSP_CTP_RST_PIN = 0xff;
const char BSP_CTP_EINT_PIN = 0xff;
const char BSP_SPEAKER_EBABLE_PIN = 0xff;
const char BSP_AUXADC_ENABLE_PIN = 0xff;
const char BSP_GNSS_POWER_PIN = 0xff;
const char BSP_BIO_SENSOR_PPG_VDRV_EN = 0xff;
const char BSP_BIO_SENSOR_32K = 0xff;
const char BSP_BIO_SENSOR_RST_PORT_PIN = 0xff;
const char BSP_BIO_SENSOR_AFE_PWD_PIN = 0xff;
const char BSP_WIFI_32K_PIN = 0xff;
const char BSP_WIFI_26M_PIN = 0xff;
const char BSP_WIFI_RESET_PIN = 0xff;
const char BSP_WIFI_ENABLE_PIN = 0xff;
const char BSP_LED0_PIN = 0xff;
const char BSP_LED1_PIN = 0xff;
const char BSP_LED2_PIN = 0xff;
const char BSP_EINTKEY0_PIN = 0xff;
const char BSP_EINTKEY1_PIN = 0xff;
const char BSP_EINTKEY2_PIN = 0xff;





