/*
 * Generated by MTK Easy PinMux Tool Version 2.0.1 for 7687. Copyright MediaTek Inc. (C) 2015.
 * 2017-01-27 14:46:43:0522
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const unsigned char BSP_CTP_EINT = 0xff;
const unsigned char HAL_ACCDET_EINT = 0xff;
const unsigned char HAL_MSDC_EINT = 0xff;
const unsigned char BSP_GNSS_EINT = 0xff;
const unsigned char BSP_WIFI_EINT = 0xff;
const unsigned char BSP_EINTKEY0_EINT = 0xff;
const unsigned char BSP_EINTKEY1_EINT = 0xff;
const unsigned char BSP_EINTKEY2_EINT = 0xff;



